session_config:
  session_expiration_time: 60
  carry_over_slots_to_new_session: false
  
intents:
- greet
- intent_user_liked
- intent_user_disliked
- user_wants_pay
- faq_ari
- faq_ccpa
- faq_escrow
- faq_gi
- faq_heloc
- faq_ii
- faq_pdp
- faq_pi
- faq_pt
- faq_rlt
- faq_sm
- canned_generic_MDA_breakup
- canned_pmt_change_dd
- canned_generic_due_date
- canned_generic_FICO
- canned_pmt_other_fees
- canned_pmt_late_fee
- canned_pmt_nsf
- canned_generic_outst_balance
- canned_pmt_breakdown
- canned_escrow_disbursal
- canned_pmt_change_reason
- covid_support
- srp_payment_options
- otd_payment_options
- otd_chat_selected
- otd_mail_selected
- otd_phone_selected
- srp_chat_selected
- srp_online_selected
- srp_mail_selected



slots:
  customer_bank_name:
    type: unfeaturized
    auto_fill: false

  customer_account_number:
    type: unfeaturized
    auto_fill: false

  customer_mobile_number:
    type: unfeaturized
    auto_fill: false

  ssn_digits:
    type: unfeaturized
    auto_fill: false

  cycle_date:
    type: unfeaturized
    auto_fill: false



responses:
  utter_covid_support:
    - text: "Our thoughts are with those affected by the COVID-19 pandemic and we are responding proactively to help you. We know that you may have questions about your mortgage. We want to help you understand the options available to you and will keep you updated as conditions continue to change and new information is available. To help provide peace of mind during these unprecedented times, Rushmore is taking numerous steps.\n\nWe are suppressing all negative credit reporting for the months of March, April and May. If your loan is current, we will continue to report your positive credit status. No late fees will be assessed for any of our customers impacted by COVID-19.\n\nYou can find more information on getting assistance at https://www.rushmorelm.com/covid-19-assistance-information/." 
  
  utter_ask_customer_bank_name:
    - text: "Please enter your Bank Name"

  utter_ask_customer_account_number:
    - text: "Please enter your Account Number"

  utter_ask_customer_mobile_number:
    - text: "Please enter your Mobile Number"

  utter_ask_ssn_digits:
    - text: "Please enter the last 4 digits of your SSN "

  utter_ask_cycle_date:
    - text: "Please enter your desired cycle date for each month"


  utter_greet_with_buttons:
  - text: Hey! I'm Fala. Let me know if you need any help. Here are some suggestions!
    buttons:
    - title: Last Payment Status
      payload: Last Payment Status
    - title: Latest FICO
      payload: Latest FICO
    - title: Monthly Due Amount
      payload: Monthly Due Amount
    - title: Due Date
      payload: Due Date
    - title: E-Statement Billing
      payload: E-Statement Billing

  utter_apologize:
  - Aw man, sorry I couldn't help! Please contact us at _______ or drop an email at ________ and we'll be glad to help you! 

  utter_happy:
  - Awesome, really glad I could help!

  utter_payment_options:
  - text: "You can select either of the following options for making payments"
    buttons:
    - title: Schedule Recurring payment
      payload: /srp_payment_options
    - title: One Time Draft Payment
      payload: /otd_payment_options
      
  utter_otd_payment_options:
  - text: "We offer the following means of payment for One Time Draft payments"
    buttons:
    - title: Pay by Mail
      payload: /otd_mail_selected
    - title: Pay by Phone
      payload: /otd_phone_selected
    - title: Pay Online through Chat
      payload: /otd_chat_selected

  utter_srp_payment_options:
  - text: "Our auto draft payment option is easy to set up and convenient to use. View our quick video tutorials to set up automatic payment online or to set up automatic payment by mail or fax or help me to setup it for you.\nWe offer the following means of payment for Scheduled Recurring Payments"
    buttons:
    - title: Pay by Mail
      payload: /srp_mail_selected
    - title: Pay Online 
      payload: /srp_online_selected
    - title: Help me get set up
      payload: /srp_chat_selected

  utter_otd_mail:
  - text: "Rushmore accepts payments by mail, accompanied by your billing coupon. Please note that payments received after 3 pm daily, and all payments received on weekends or holidays, will be processed the next business day. Payments are effective as of the date they are received.\nYou may send payments to: Rushmore Loan Management Services LLC, PO Box 514707, Los Angeles, CA 90051-4707.\nFor Overnight Payments: You may send payments to: Rushmore Loan Management Services LLC, 15480 Laguna Canyon Road, Suite 100, Irvine, CA 92618."
  
  utter_otd_phone:
  - text: "Please call our toll-free Automated Loan Information Hotline by dialing 888-504-6700. The system will prompt you to enter your account number and the last four digits of your Social Security number for verification purposes. Upon verification, you will be offered various menu prompts including but not limited to: the ability to access information regarding your account, make payments via phone, and/or speak with a live representative to update your account information. You may make an automated payment by phone for a service charge of $5.00 or with a live agent for a service charge of $10.00. The service charge may be non-refundable."
    
  utter_srp_mail:
    - text: "You can find information on setting up an SRP via mail here: https://www.rushmorelm.com/setting-auto-draft-payments-mail-fax/"
      
  utter_srp_online:
    - text: "You can find information on setting up an SRP yourself online here: https://www.rushmorelm.com/setting-auto-draft-payments-online/"



actions:
- action_default_fallback
- action_trigger_faq
- action_get_canned_dynamic_response



forms:
- srp_payment_form
- otd_payment_form