session_config:
  session_expiration_time: 60
  carry_over_slots_to_new_session: false
  
intents:
- greet
- intent_user_liked
- intent_user_disliked
- train_data
- faq_ari
- faq_ccpa
- faq_escrow
- faq_gi
- faq_heloc
- faq_ii
- faq_pdp
- faq_pi
- faq_pt
- faq_rlt
- faq_sm
- canned_generic_MDA_breakup
- canned_pmt_change_dd
- canned_generic_due_date
- canned_generic_FICO
- canned_pmt_other_fees
- canned_pmt_late_fee
- canned_pmt_nsf
- canned_generic_outst_balance
- canned_pmt_breakdown
- canned_generic_escrow_disbursal
- canned_pmt_change_reason

slots:
  is_admin:
    type: bool

  faq_intended_section:
    type: unfeaturized
    auto_fill: false
  
  faq_intended_question:
    type: unfeaturized
    auto_fill: false

  faq_userinput_question:
    type: unfeaturized
    auto_fill: false


responses:
  action_default_fallback:
  - Sorry, didn't quite get that.

  utter_greet_with_buttons:
  - text: Hey! I'm Fala. Let me know if you need any help. Here are some suggestions!
    buttons:
    - title: Last Payment Status
      payload: Last Payment Status
    - title: Latest FICO
      payload: Latest FICO
    - title: Monthly Due Amount
      payload: Monthly Due Amount
    - title: Due Date
      payload: Due Date
    - title: E-Statement Billing
      payload: E-Statement Billing

  utter_fix_faq:
  - Alright, let's fix that. 

  utter_ask_faq_userinput_question:
  - text: Please type in the question that didn't respond correctly.

  utter_ask_faq_intended_section:
  - text: What category was your intended answer in? 
    buttons:
    - title: "Recent Loan Transfers"
      payload: 'rlt'
    - title: "Home Equity Line-of-Credit"
      payload: 'heloc'
    - title: "Payment Information"
      payload: 'pi'
    - title: "Past Due Payments"
      payload: 'pdp'
    - title: "Property Taxes"
      payload: 'pt'
    - title: "Insurance Information"
      payload: 'ii'
    - title: "Escrow Information"
      payload: 'escrow'
    - title: "Adjustable Rate Information"
      payload: 'ari'
    - title: "General Information"
      payload: 'gi'
    - title: "Service Members"
      payload: 'sm'
    - title: "California Consumer Privacy Act (CCPA)"
      payload: 'ccpa'

  utter_confirm_fix_faq:
  - Alright, I've sent this data to our knowledge base, it should get updated soon. Thanks for your help!

  utter_apologize:
  - Aw man, sorry I couldn't help! Please contact us at _______ or drop an email at ________ and we'll be glad to help you! 

  utter_happy:
  - Awesome, really glad I could help!

  utter_admin_detection_failed:
  - Sorry, I couldn't verify if you're an admin. Please contact a developer about this!


actions:
- action_default_fallback
- action_send_faq_data
- action_trigger_faq
- action_get_canned_dynamic_response
- action_get_is_admin


forms:
- faq_fix_form
