conn_info = {
        'host': '18.235.50.52',
        'port': 5433,
        'user': 'dbadmin',
        'password': 'P0tom@c@207',
        'database': 'POTOMACDB',
        # autogenerated session label by default,
        'session_label': 'chatbot',
        # default throw error on invalid UTF-8 results
        'unicode_error': 'strict',
        # SSL is disabled by default
        'ssl': False,
        # using server-side prepared statements is disabled by default
        'use_prepared_statements': False,
        # connection timeout is not enabled by default
        # 5 seconds timeout for a socket operation (Establishing a TCP connection or read/write operation)
        'connection_timeout': 5}

schema_name = "Chatbot_POC_New"
canned_dynamic_responses_table = "RLMS_CUSTOMER_CANNED_DYNAMIC_RESPONSES"
canned_dynamic_responses_data_table = "RLMS_CUSTOMER_CANNED_DYNAMIC_RESPONSES_DATA"

